/**
 * esbuild 配置脚本（参考实现）
 * 
 * 本脚本是参考实现，可以根据项目实际情况进行适配或替换。
 * 可以使用其他构建工具（Vite、Rollup、Webpack 等），但必须遵守核心行为规范：
 * 
 * 核心行为规范（必须遵守）：
 * - 构建产物输出到 dist/{pluginName}/main.js（pluginName 来自 manifest.name）
 * - 遵守目录命名规范：当前项目用 manifest.id，上级目录用 manifest.name
 * - 实现自动复制到 Obsidian 插件目录
 * - 复制操作失败不应中断构建过程
 * 
 * 可适配的部分：
 * - 构建工具选择（esbuild、Vite、Rollup 等）
 * - CSS 处理方式（构建、复制、跳过）
 * - 热重载支持（可选）
 * - 构建模式配置（生产/开发）
 */

import builtins from "builtin-modules";
import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import { fileURLToPath } from "url";
import { dirname } from "path";

// 获取当前文件的目录（scripts 目录）
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// 项目根目录（scripts 的上级目录）
const PROJECT_ROOT = path.resolve(__dirname, "..");

/*
 * CSS构建逻辑说明：
 * 
 * 本配置文件支持两种CSS处理场景：
 * 
 * 场景A：已有CSS文件的项目
 * - 检测到 styles.css 文件时
 * - 直接复制现有CSS文件到目标目录
 * - 适用于不需要编译的纯CSS项目
 * 
 * 场景B：项目没有CSS文件
 * - 没有检测到任何CSS相关文件时
 * - 跳过CSS处理，仅处理其他静态文件
 * - 适用于纯JavaScript插件项目
 * 
 * 核心原则：
 * - [OK] 直接复制现有CSS文件到目标目录
 * - [OK] 使用 path.join(outDir, 'styles.css') 确保路径正确
 * - [OK] 构建产物集中管理到 dist/{plugin-name}/ 目录
 */

// ========== 配置区域 ==========
// 是否启用自动复制插件到 Obsidian 插件目录的功能
const AUTO_COPY_TO_OBSIDIAN = true;
// 是否启用 .hotreload 文件功能（包括构建时创建和复制到 Obsidian 插件目录）
const ENABLE_HOTRELOAD = true;
// 是否启用复制构建产物到上级目录的功能
// 此功能会将构建产物复制到上级目录的 .obsidian/plugins/{pluginName}/ 目录
const COPY_TO_PARENT_REPO = true;
// ==============================

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// 从 manifest.json 读取插件信息
const manifest = JSON.parse(fs.readFileSync(path.join(PROJECT_ROOT, "manifest.json"), "utf-8"));
const pluginId = manifest.id;
const pluginName = manifest.name;
const outDir = path.join(PROJECT_ROOT, `dist/${pluginName}`);

// 显示构建信息
console.log("\n" + "=".repeat(60));
console.log(`[BUILD] 开始构建插件: ${pluginName}`);
console.log(`   ID: ${pluginId}`);
console.log(`   版本: ${manifest.version}`);
console.log(`   模式: ${prod ? "生产模式 (Production)" : "开发模式 (Development)"}`);
console.log("=".repeat(60));

// 确保输出目录存在
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

// 复制静态文件到输出目录的函数
const copyStaticFiles = () => {
    try {
        console.log(`\n[FILE] [${pluginName}] 正在复制资源文件到构建目录...`);
        console.log(`   目标目录: ${outDir}`);
        
        // CSS 文件已经由 build-css.mjs 直接输出到 dist/{pluginName}/styles.css
        // 这里只需要检查文件是否存在即可
        const stylesCssPath = path.join(outDir, "styles.css");
        if (fs.existsSync(stylesCssPath)) {
            console.log("   [OK] 样式文件 styles.css（已由 build-css.mjs 生成）");
        } else {
            console.log("   [WARNING] 未找到样式文件 styles.css");
            console.log("      提示：请确保 build-css.mjs 已成功执行");
        }
        
        // 复制 manifest.json
        const manifestPath = path.join(PROJECT_ROOT, "manifest.json");
        if (fs.existsSync(manifestPath)) {
            fs.copyFileSync(manifestPath, path.join(outDir, "manifest.json"));
            console.log("   [OK] 插件清单 manifest.json");
        }
        
        // 创建 .hotreload 文件（在构建过程中）
        if (ENABLE_HOTRELOAD) {
            try {
                const hotreloadPath = path.join(outDir, ".hotreload");
                fs.writeFileSync(hotreloadPath, "");
                console.log("   [OK] 热重载文件 .hotreload");
            } catch (error) {
                console.log("   [WARNING] 创建热重载文件失败:");
                console.log(`      错误: ${error instanceof Error ? error.message : error}`);
            }
        } else {
            console.log("   [INFO] 热重载功能已禁用，跳过 .hotreload 文件创建");
        }
        
        console.log(`   [OK] [${pluginName}] 资源文件复制完成`);
    } catch (error) {
        console.log(`   [ERROR] [${pluginName}] 复制资源文件时发生错误:`);
        console.log(`      错误: ${error instanceof Error ? error.message : error}`);
        throw error;
    }
};

// 递归复制目录的函数
/**
 * @param {string} src - 源目录路径
 * @param {string} dest - 目标目录路径
 * @param {{ count: number }} copiedCount - 已复制的文件数量（内部使用）
 * @returns {number} - 复制的文件总数
 */
const copyDirectory = (src, dest, copiedCount = { count: 0 }) => {
    // 创建目标目录
    if (!fs.existsSync(dest)) {
        fs.mkdirSync(dest, { recursive: true });
    }

    // 读取源目录中的所有文件和子目录
    const entries = fs.readdirSync(src, { withFileTypes: true });

    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);

        if (entry.isDirectory()) {
            // 递归复制子目录
            copyDirectory(srcPath, destPath, copiedCount);
        } else {
            // 复制文件（直接覆盖）
            fs.copyFileSync(srcPath, destPath);
            copiedCount.count++;
            console.log(`     [OK] ${entry.name}`);
        }
    }

    return copiedCount.count;
};

// 在父级目录中查找 .obsidian/plugins 目录
/**
 * @param {string} startDir - 开始查找的目录
 * @returns {string | null} - 找到的 plugins 目录路径，未找到则返回 null
 */
const findObsidianPluginsDir = startDir => {
    let currentDir = path.resolve(startDir);
    const root = path.parse(currentDir).root;

    console.log(`[SEARCH] [${pluginName}] 正在查找 Obsidian 插件目录...`);

    // 向上遍历目录树
    while (currentDir !== root) {
        // 检查当前目录的父目录
        const parentDir = path.dirname(currentDir);
        const obsidianDir = path.join(parentDir, ".obsidian");

        if (fs.existsSync(obsidianDir) && fs.statSync(obsidianDir).isDirectory()) {
            const pluginsDir = path.join(obsidianDir, "plugins");
            if (fs.existsSync(pluginsDir) && fs.statSync(pluginsDir).isDirectory()) {
                console.log(`   [OK] 找到插件目录: ${pluginsDir}`);
                return pluginsDir;
            }
        }

        // 移动到父目录
        currentDir = parentDir;
    }

    console.log("   [ERROR] 未找到 Obsidian 插件目录");
    return null;
};

// 复制构建产物到上级目录的 .obsidian/plugins/ 目录
const copyToParentRepo = () => {
    console.log("\n" + "=".repeat(50));
    console.log(`[PACKAGE] [${pluginName}] 复制构建产物到上级目录`);
    console.log("=".repeat(50));

    if (!COPY_TO_PARENT_REPO) {
        console.log("[WARNING] 复制到上级目录功能已禁用");
        console.log("=".repeat(50) + "\n");
        return;
    }

    try {
        // 查找上级目录的 .obsidian/plugins 目录
        const pluginsDir = findObsidianPluginsDir(PROJECT_ROOT);

        if (!pluginsDir) {
            console.log(`\n[WARNING] [${pluginName}] 跳过复制：未找到上级目录的 Obsidian 插件目录`);
            console.log("   提示：此功能需要项目位于 Obsidian 仓库的子目录中");
            console.log("=".repeat(50) + "\n");
            return;
        }

        // 目标目录：上级目录的 .obsidian/plugins/{pluginName}
        const targetDir = path.join(pluginsDir, pluginName);

        // 检查源目录是否存在
        if (!fs.existsSync(outDir)) {
            console.log(`\n[WARNING] [${pluginName}] 跳过复制：源目录不存在`);
            console.log(`   源目录: ${outDir}`);
            console.log("=".repeat(50) + "\n");
            return;
        }

        console.log(`\n[FOLDER] [${pluginName}] 开始复制文件...`);
        console.log(`   源目录: ${outDir}`);
        console.log(`   目标目录: ${targetDir}`);

        // 检查目标目录是否存在
        const isUpdate = fs.existsSync(targetDir);
        if (isUpdate) {
            console.log("   [INFO] 目标目录已存在，将更新现有文件");
        } else {
            console.log("   [INFO] 目标目录不存在，将创建新目录");
        }

        console.log("\n   正在复制文件:");
        // 复制整个插件目录
        const fileCount = copyDirectory(outDir, targetDir);

        console.log(`\n   [OK] 插件 [${pluginName}] 复制成功！`);
        console.log(`   文件数量: ${String(fileCount)} 个`);
        console.log(`   版本: v${manifest.version}`);
        if (isUpdate) {
            console.log(`   状态: 已更新到最新版本`);
        } else {
            console.log(`   状态: 已复制到上级目录`);
        }

        // 处理 .hotreload 文件
        if (ENABLE_HOTRELOAD) {
            try {
                const hotreloadPath = path.join(targetDir, ".hotreload");
                
                // 如果构建目录中有 .hotreload 文件，则复制它
                const sourceHotreloadPath = path.join(outDir, ".hotreload");
                if (fs.existsSync(sourceHotreloadPath)) {
                    fs.copyFileSync(sourceHotreloadPath, hotreloadPath);
                    console.log("\n   [HOT] 热重载文件已复制");
                } else {
                    // 否则创建新的 .hotreload 文件
                    fs.writeFileSync(hotreloadPath, "");
                    console.log("\n   [HOT] 热重载文件已创建");
                }
                console.log("   提示：需要安装 Hot-Reload 插件才能使用此功能");
            } catch (error) {
                console.log("\n   [WARNING] 热重载文件处理失败:");
                console.log(`      错误: ${error instanceof Error ? error.message : error}`);
            }
        } else {
            // 如果选项被关闭，清理目标目录的 .hotreload 文件
            const hotreloadPath = path.join(targetDir, ".hotreload");
            if (fs.existsSync(hotreloadPath)) {
                try {
                    fs.unlinkSync(hotreloadPath);
                    console.log("\n   [DELETE] 热重载文件已删除（功能已禁用）");
                } catch (error) {
                    console.log("\n   [WARNING] 删除热重载文件失败:");
                    console.log(`      错误: ${error instanceof Error ? error.message : error}`);
                }
            } else {
                console.log("\n   [INFO] 未找到热重载文件，无需清理");
            }
        }
        if (ENABLE_HOTRELOAD) {
            console.log("\n   [TIP] 提示：Hot-Reload 插件将自动重载更新");
        } else {
            console.log("\n   [TIP] 提示：重启 Obsidian 或禁用后重新启用插件以加载最新版本");
        }
        console.log("=".repeat(50) + "\n");
    } catch (error) {
        console.log(`\n   [ERROR] [${pluginName}] 复制失败！`);
        console.log(`      错误: ${error instanceof Error ? error.message : error}`);
        console.log("=".repeat(50) + "\n");
        // 不抛出错误，避免中断构建过程
    }
};

// 复制插件到 Obsidian 插件目录
const copyToObsidianPlugins = () => {
    console.log("\n" + "=".repeat(50));
    console.log(`[PACKAGE] [${pluginName}] 自动复制插件到 Obsidian`);
    console.log("=".repeat(50));

    if (!AUTO_COPY_TO_OBSIDIAN) {
        console.log("[WARNING] 自动复制功能已禁用");
        console.log("=".repeat(50) + "\n");
        return;
    }

    try {
        // 查找 .obsidian/plugins 目录
        const pluginsDir = findObsidianPluginsDir(PROJECT_ROOT);

        if (!pluginsDir) {
            console.log(`\n[WARNING] [${pluginName}] 跳过自动复制：未找到 Obsidian 仓库`);
            console.log("   提示：此功能仅在项目位于 Obsidian 仓库内部或其子目录时有效");
            console.log("=".repeat(50) + "\n");
            return;
        }

        // 目标目录：.obsidian/plugins/插件ID
        const targetDir = path.join(pluginsDir, pluginId);

        console.log(`\n[FOLDER] [${pluginName}] 开始复制文件...`);
        console.log(`   源目录: ${outDir}`);
        console.log(`   目标目录: ${targetDir}`);

        // 检查目标目录是否存在
        const isUpdate = fs.existsSync(targetDir);
        if (isUpdate) {
            console.log("   [INFO] 目标目录已存在，将更新现有插件");
        } else {
            console.log("   [INFO] 目标目录不存在，将安装新插件");
        }

        console.log("\n   正在复制文件:");
        // 复制整个插件目录
        const fileCount = copyDirectory(outDir, targetDir);

        console.log(`\n   [OK] 插件 [${pluginName}] 复制成功！`);
        console.log(`   文件数量: ${String(fileCount)} 个`);
        if (isUpdate) {
            console.log(`   状态: 已更新到最新版本 (v${manifest.version})`);
        } else {
            console.log(`   状态: 插件已安装到 Obsidian (v${manifest.version})`);
        }

        // 处理 .hotreload 文件
        if (ENABLE_HOTRELOAD) {
            try {
                const hotreloadPath = path.join(targetDir, ".hotreload");
                
                // 如果构建目录中有 .hotreload 文件，则复制它
                const sourceHotreloadPath = path.join(outDir, ".hotreload");
                if (fs.existsSync(sourceHotreloadPath)) {
                    fs.copyFileSync(sourceHotreloadPath, hotreloadPath);
                    console.log("\n   [HOT] 热重载文件已复制");
                } else {
                    // 否则创建新的 .hotreload 文件
                    fs.writeFileSync(hotreloadPath, "");
                    console.log("\n   [HOT] 热重载文件已创建");
                }
                console.log("   提示：需要安装 Hot-Reload 插件才能使用此功能");
            } catch (error) {
                console.log("\n   [WARNING] 热重载文件处理失败:");
                console.log(`      错误: ${error instanceof Error ? error.message : error}`);
            }
        } else {
            // 如果选项被关闭，清理远程的 .hotreload 文件
            const hotreloadPath = path.join(targetDir, ".hotreload");
            if (fs.existsSync(hotreloadPath)) {
                try {
                    fs.unlinkSync(hotreloadPath);
                    console.log("\n   [DELETE] 热重载文件已删除（功能已禁用）");
                } catch (error) {
                    console.log("\n   [WARNING] 删除热重载文件失败:");
                    console.log(`      错误: ${error instanceof Error ? error.message : error}`);
                }
            } else {
                console.log("\n   [INFO] 未找到热重载文件，无需清理");
            }
        }
        if (ENABLE_HOTRELOAD) {
            console.log("\n   [TIP] 提示：Hot-Reload 插件将自动重载更新");
        } else {
            console.log("\n   [TIP] 提示：重启 Obsidian 或禁用后重新启用插件以加载最新版本");
        }
        console.log("=".repeat(50) + "\n");
    } catch (error) {
        console.log(`\n   [ERROR] [${pluginName}] 复制失败！`);
        console.log(`      错误: ${error instanceof Error ? error.message : error}`);
        console.log("=".repeat(50) + "\n");
        // 不抛出错误，避免中断构建过程
    }
};

let outfile = path.join(outDir, "main.js");
const devtargetPath = path.join(PROJECT_ROOT, ".devtarget");
if (fs.existsSync(devtargetPath)) {
    const outFolderOverride = fs.readFileSync(devtargetPath, "utf8").trim().split("\n")
        .map(line => line.trim()).find(line => !line.startsWith("#") && !line.startsWith("//"));
    if (outFolderOverride) {
        outfile = path.join(outFolderOverride, "main.js");
        console.log(`[TOOL] [${pluginName}] 临时输出位置:`, outfile);
    }
}

// 构建配置
const buildOptions = {
    banner: { js: banner },
    entryPoints: [path.join(PROJECT_ROOT, "src/main.ts")],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
        // Node.js 内置模块（node: 前缀）
        "node:process",
        "node:stream",
        "node:fs",
        "node:path",
        "node:util",
        "node:events",
        "node:buffer",
        "node:crypto",
        "node:os",
        "node:url",
        "node:net",
        "node:tls",
        "node:http",
        "node:https",
        "node:zlib",
        "node:readline",
        "node:child_process",
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    minify: prod,
    platform: "browser",
    treeShaking: true,
    outfile,
    plugins: [
        {
            name: "copy-static-files",
            setup(build) {
                build.onEnd(() => {
                    // 仅在输出到 dist 目录时复制静态文件
                    if (outfile.startsWith(outDir)) {
                        copyStaticFiles();
                    }
                });
            },
        },
        {
            name: "copy-to-obsidian",
            setup(build) {
                build.onEnd(() => {
                    // 仅在输出到 dist 目录时复制到 Obsidian 插件目录
                    if (outfile.startsWith(outDir)) {
                        copyToObsidianPlugins();
                    }
                });
            },
        },
        {
            name: "copy-to-parent-repo",
            setup(build) {
                build.onEnd(() => {
                    // 仅在输出到 dist 目录时复制到上级目录
                    if (outfile.startsWith(outDir)) {
                        copyToParentRepo();
                    }
                });
            },
        },
    ],
};

if (prod) {
    // 生产模式：使用一次性构建，不使用缓存，确保从头构建
    console.log(`\n[BUILD] [${pluginName}] 开始编译 TypeScript 代码...`);
    
    const result = await esbuild.build(buildOptions);
    
    // 检查构建结果
    if (result.errors.length > 0) {
        console.error(`\n[ERROR] [${pluginName}] 构建失败！`);
        console.error(`   错误数量: ${result.errors.length}`);
        result.errors.forEach((error, index) => {
            console.error(`\n   错误 ${index + 1}:`);
            console.error(`   ${error.text}`);
            if (error.location) {
                console.error(`   位置: ${error.location.file}:${error.location.line}:${error.location.column}`);
            }
        });
        process.exit(1);
    }
    
    if (result.warnings.length > 0) {
        console.warn(`\n[WARNING] [${pluginName}] 构建警告:`);
        result.warnings.forEach((warning, index) => {
            console.warn(`   警告 ${index + 1}: ${warning.text}`);
        });
    }
    
    // 构建成功后，插件回调会自动执行复制操作
    console.log(`\n[OK] [${pluginName}] TypeScript 编译完成`);
    
    // 验证构建产物
    const mainJsPath = path.join(outDir, "main.js");
    if (fs.existsSync(mainJsPath)) {
        const stats = fs.statSync(mainJsPath);
        console.log(`   [OK] 构建产物已生成: ${mainJsPath}`);
        console.log(`   [OK] 文件大小: ${(stats.size / 1024).toFixed(2)} KB`);
    } else {
        console.error(`   [ERROR] 构建产物不存在: ${mainJsPath}`);
        process.exit(1);
    }
    
    console.log("\n" + "=".repeat(60));
    console.log(`[OK] [${pluginName}] 构建完成！`);
    console.log(`   版本: ${manifest.version}`);
    console.log(`   输出目录: ${outDir}`);
    console.log("=".repeat(60) + "\n");
    process.exit(0);
} else {
    // 开发模式：使用 context 进行增量构建和监听
    const context = await esbuild.context(buildOptions);
    console.log(`\n[WATCH] [${pluginName}] 正在监听文件变化...`);
    console.log(`   输出目录: ${outDir}`);
    console.log("   提示：修改源文件将自动重新构建\n");
    await context.watch();
}